[package]
name = "peripheral_linux"
version = "0.1.0"
authors = ["Samuel Dolt <samuel@dolt.ch>"]

[dependencies]
peripheral = { git="https://github.com/samdolt/peripheral.git", features=["default", "use_std"]}
sysfs_gpio = "0.4"
